-- Add short_id column to lessons table for SEO-friendly URLs
-- Following industry standard (Medium, Amazon) with 10-character alphanumeric IDs

-- Add short_id column
ALTER TABLE lessons ADD COLUMN short_id VARCHAR(12) UNIQUE;

-- Add index for fast lookups
CREATE INDEX idx_lessons_short_id ON lessons(short_id);

-- Add comment explaining the column
COMMENT ON COLUMN lessons.short_id IS 'Short alphanumeric ID for SEO-friendly URLs (e.g., k5b8x2p9m1).';

-- Note: Short IDs will be generated by the application using nanoid
-- Existing lessons will need their short_ids populated via a data migration script
-- For now, this column is nullable to allow gradual migration
